### ISSUE TITLE
Use the admin folder to put there your routes

### ISSUE THREAD

**Issue by AnderCabrera** [Chejinos-Kinal/online-bank-frontend#22]
@fpaiz-2022134 
Put the admin routes inside admin folder by creating a new .js file. The files you must fix are the following:

`products.service.js`
`typeAccount.service.js`

**Remember to update the `import` of those files that use the files mentioned above.**

**Comment by fpaiz-2022134** [comment]
Done.

**Comment by AnderCabrera** [comment]
#23
